// src/utils/country-map.ts

export const countryToISO: Record<string, string> = {
  "Alemanha": "de",
  "Áustria": "at",
  "Bulgária": "bg",
  "Grécia": "gr",
  "Finlândia": "fi",
  "China": "cn",
  "Japão": "jp",
  "Rússia": "ru",
  "Brasil": "br",
  "Canadá": "ca",
  "Sérvia": "rs",
  "Itália": "it",
  "Holanda": "nl",
  "França": "fr",
  "Bélgica": "be",
  "Polônia": "pl",
  "Argentina": "ar",
  "Hungria": "hu",
  "Índia": "in",
  "Estados Unidos": "us",
  "Cazaquistão": "kz",
  "República Tcheca": "cz",
  "Reino Unido": "gb",
  "Dinamarca": "dk",
  "Chile": "cl",
  "Espanha": "es",
  "Peru": "pe",
  "Noruega": "no",
  "Austrália": "au",
};
